// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


function errorToJs(param) {
  return {
          name: param.name,
          message: param.message,
          stack: param.stack
        };
}

function errorFromJs(param) {
  return {
          name: param.name,
          message: param.message,
          stack: param.stack
        };
}

exports.errorToJs = errorToJs;
exports.errorFromJs = errorFromJs;
/* No side effect */
